[package]
name = "mancala-full-search"
version = "0.1.0"
authors = ["Daiju Nakayama <42.daiju@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam = "*"
generic-array = "*"
typenum = "*"
fnv = "*"
locked-hash = { git = "https://github.com/hinohi/rust-locked-hash.git" }
